// App constants matching iOS PayCoffee app

// Model and data constants
export const MODEL_FILENAME = 'PayCoffee';
export const ITEM_SEPARATOR = ';';
export const DEFAULT_MAIL_BODY = 'email generated by iOS app PayCoffee';

// Font configuration
export const FONT_TITLE_NAME = 'Georgia-BoldItalic';
export const FONT_TITLE_SIZE = 18;
export const FONT_DETAIL_NAME = 'Georgia';
export const FONT_DETAIL_SIZE = 16;

// Layout constants
export const ROW_HEIGHT = 54;
export const TOOLBAR_HEIGHT = 44;
export const NAVIGATION_HEIGHT = 44;

// iOS Color palette (for replication)
export const IOS_COLORS = {
  // Background colors
  darkBg: '#1a1a1a',
  cellBg: 'rgba(26, 26, 26, 0.7)',
  cellBgSelected: 'rgba(255, 255, 255, 0.1)',

  // Text colors
  textPrimary: '#ffffff',
  textSecondary: '#8e8e93',

  // Credit indicator colors
  creditPositive: '#2ecc71',  // Green - credits > 0
  creditNegative: '#e74c3c',  // Red - credits < 0
  creditNeutral: '#f1c40f',   // Yellow - credits = 0

  // UI element colors
  toolbarBg: 'rgba(26, 26, 26, 0.9)',
  buttonBlue: '#007aff',
  buttonRed: '#ff3b30',

  // Separator colors
  separator: 'rgba(255, 255, 255, 0.1)',
};

// Default initial data (matching iOS app)
export const DEFAULT_PERSONS = [
  { name: 'Tony', credits: 1, date: '2012-10-28' },
  { name: 'Peter', credits: 2, date: '' },
  { name: 'Phil', credits: -3, date: '2012-10-18' },
  { name: 'Mike', credits: 0, date: '' },
];

// Storage keys
export const STORAGE_KEYS = {
  PERSONS: 'paycoffee_persons',
  LAST_UPDATE: 'paycoffee_last_update',
};

// Animation durations
export const ANIMATION_DURATION = 300;

// Touch gesture configurations
export const GESTURE_CONFIGS = {
  DOUBLE_TAP_DELAY: 300, // ms
  LONG_PRESS_DELAY: 500, // ms
};

// CSV export format
export const CSV_FORMAT = {
  SEPARATOR: ';',
  DATE_FORMAT: 'YYYY-MM-DD',
};

// Payment algorithm constants
export const PAYMENT_CONFIG = {
  CREDIT_PER_PERSON: 1,
  PAYER_MULTIPLIER: 1, // payer gains (selectedCount - 1) * this value
};

// Email export configuration
export const EMAIL_CONFIG = {
  SUBJECT: 'PayCoffee Data Export',
  BODY: 'PayCoffee data export attached.\n\nImport this data in the PayCoffee app.',
};
